// Firebase options for the GYMPASS project (gympass-7199e).
// Android values sourced from google-services.json (placed at mobile/android/app/).
// iOS values are stubs — add GoogleService-Info.plist and fill them in when targeting iOS.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw _stub;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw _stub;
    }
  }

  static UnsupportedError get _stub => UnsupportedError(
        'DefaultFirebaseOptions: replace this stub with the real '
        'firebase_options.dart generated by `flutterfire configure`. '
        'See mobile/lib/firebase_options.dart for instructions.',
      );

  // ── Replace the placeholder values below with your real project config ──
  //
  // Find them in:
  //   Firebase Console → GYMPASS project → Project settings → Your apps
  //   (or run `flutterfire configure` to regenerate this file automatically)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrooaPs1EqmWuRS6022b5v4UVaHuQarI',
    appId: '1:379561915336:android:9d37c4d6f9a8c4536d46fd',
    messagingSenderId: '379561915336',
    projectId: 'gympass-7199e',
    storageBucket: 'gympass-7199e.firebasestorage.app',
  );

  // iOS not yet configured — add GoogleService-Info.plist when targeting iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '379561915336',
    projectId: 'gympass-7199e',
    storageBucket: 'gympass-7199e.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_IOS_CLIENT_ID',
    iosBundleId: 'net.gympass.gympass',
  );
}
