// GENERATED FILE — do not edit manually.
//
// Replace this stub with the real output of:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<your-firebase-project-id>
//
// Before running flutterfire configure:
//   1. Place google-services.json at mobile/android/app/google-services.json
//   2. Place GoogleService-Info.plist at mobile/ios/Runner/GoogleService-Info.plist
//
// Until the real file is generated, Firebase.initializeApp() will throw.
// The app still builds — push notifications are silently disabled until
// the credentials are in place.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw _stub;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw _stub;
    }
  }

  static UnsupportedError get _stub => UnsupportedError(
        'DefaultFirebaseOptions: replace this stub with the real '
        'firebase_options.dart generated by `flutterfire configure`. '
        'See mobile/lib/firebase_options.dart for instructions.',
      );

  // ── Replace the placeholder values below with your real project config ──
  //
  // Find them in:
  //   Firebase Console → GYMPASS project → Project settings → Your apps
  //   (or run `flutterfire configure` to regenerate this file automatically)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: 'REPLACE_WITH_REAL_APP_ID',
    messagingSenderId: 'REPLACE_WITH_REAL_SENDER_ID',
    projectId: 'REPLACE_WITH_REAL_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_REAL_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: 'REPLACE_WITH_REAL_APP_ID',
    messagingSenderId: 'REPLACE_WITH_REAL_SENDER_ID',
    projectId: 'REPLACE_WITH_REAL_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_REAL_STORAGE_BUCKET',
    iosClientId: 'REPLACE_WITH_REAL_IOS_CLIENT_ID',
    iosBundleId: 'REPLACE_WITH_REAL_IOS_BUNDLE_ID',
  );
}
